[localhost]
templateDirectory=_template
cssDir=_css
jsDir=_js
masterPage=master.tpl
racineProject=http://127.0.0.1/MutuForumV2
hostProject=http://192.168.1.125/MutuForumV2
imageDirectory=img
[BDD]
host=localhost
user =root
mdp =
bdd = forum
#host=db5015586136.hosting-data.io
#user =dbu1394089
#mdp =L@lilulelo01
#bdd=dbs12729949